const print1 = () => console.log(1)
const print2 = () => console.log(2)
const print3 = () => console.log(3)

setTimeout(print1, 0)
setTimeout(print2, 0)
setTimeout(print3, 0)
console.log(4)
console.log(5)
console.log(5)
console.log(5)
console.log(5)
console.log(5)
console.log(5)
console.log(5)
console.log(5)
console.log(5)
console.log(5)
console.log(5)
console.log(5)
console.log(5)
console.log(5)